### ISSUE TITLE
Proposal: Apple TV Development

### ISSUE THREAD

**Issue by reden87** [NSBudapest/NSBudapestMeetup#17]
**Apple TV Development**

Last year Apple introduced the fourth generation Apple TV and with that a new operating system called tvOS.
The new platform offers the ability for developers to create and submit application to the new tvOS App Store.

In this talk I’ll introduce you this platform: we’ll talk about the core concept of tvOS, the concept of navigation and some development related topics too.

Agenda:
- The living room experience
- Focus model
- Top Shelf
- On-Demand Resources

**Gergo Nemeth**
iOS developer
[@reden87](https://twitter.com/reden87)

**Supercharge Ltd.**
[http://www.supercharge.io/](http://www.supercharge.io/)

**Comment by davidkovaccs** [comment]
👍

**Comment by viktorbenei** [comment]
I'd totally dig this ;)

**Comment by reden87** [comment]
@vasarhelyia attached my slides

[tvOS NSBudapest.pdf](https://github.com/NSBudapest/NSBudapestMeetup/files/559038/tvOS.NSBudapest.pdf)
