### ISSUE TITLE
Proposal for my Swift talk

### ISSUE THREAD

**Issue by lorentey** [NSBudapest/NSBudapestMeetup#2]
Wat about Swift?
Károly Lőrentey

Swift is Apple's recently created programming language with no source or link-time compatibility, or even a working compiler. In this extremely serious talk for professional software engineers, we are going to take a quick look at the current state of the Swift language, compiler and ecosystem. 

Karoly originally started mobile programming for Palm OS. After being sidetracked as an employee of Charles Simonyi and then LogMeIn, he is now back on mobile platforms, as an intrepid indie developer wannabe on iOS. He hasn't shipped anything yet, and would you please stop asking him about a ship date.

**Comment by vasarhelyia** [comment]
wow, :+1: thanks!

**Comment by bloodrabbit** [comment]
awesome, cheers! 🚀 what's the ship date?

**Comment by lorentey** [comment]
Grrr
