### ISSUE TITLE
Talk proposals

### ISSUE THREAD

**Issue by almostintuitive** [NSBudapest/NSBudapestMeetup#21]
Hi!

I hope I'll be able to attend the March or April meetup.
I have a few drafts and I'd be happy to expand to a proper talks by then:

1. "The Emperor’s New Clothes" - an example-based exploration of the different styles of programming (procedural, functional, object-oriented)
2. statefull, stateless, single app state, distributed/local state - how we think of them from a technical & business perspective.
3. transitioning a production obj-c to swift iteratively - a detailed case study (gotchas)
4. optimising for revenue per employee - from a technical perspective
5. you don’t need an ORM (in some cases at least)
6. optimisation in the functional world (no, it doesn’t matter how many times you loop over an array. yes, you can speed up your "functionally-written" operations by 5-10x).

Let me know if you'd be interested to hear any of these!
Depending on the usual length of the talks, I can also mash some of these together into one presentation.

Thanks!

**Comment by vasarhelyia** [comment]
we could make this work even in February! I'd vote for 1. and 2. merged into an hour long talk. ✌️

**Comment by andrassomogyi** [comment]
3. would be really useful for me nowadays, but @vasarhelyia 's choice also sounds great.

**Comment by almostintuitive** [comment]
hour long??😱

can I rather do half an hour?
I don't think I can put together an enganging hour long presentation:P

happy to do Q&A after though for as long as there are questions - but I
definitely want to give others a chance to present, too!

**Comment by vasarhelyia** [comment]
haha alright! it's up to you, of course. 😊

**Comment by almostintuitive** [comment]
A quick update: 

I'm writing a blogpost about:
3. transitioning a production obj-c to swift iteratively - a detailed case study (gotchas)
So this won't be part of what I'll be talking about. Will send a link when it's ready (ETA tomorrow evening)

The talk will be a mix of the following two proposals, following @vasarhelyia's advice:
1. "The Emperor’s New Clothes" - an example-based exploration of the different styles of programming (procedural, functional, object-oriented)
2. statefull, stateless, single app state, distributed/local state - how we think of them from a technical & business perspective.

I think they are connected, so it won't be super difficult to talk about both in one presentation.

Does that sound good?

**Comment by almostintuitive** [comment]
Questions:
1. By default, I'd be talking in English - is that the preferred language?
2. How do you guys feel about watching someone live coding? (as that being part of the presentation) I mean this can obviously have disastrous consequences :P

**Comment by lajosdavid** [comment]
1. Yes, English is the meetup's main language, often have some foreign attendees too.
2. Live coding is always fun! 😃 Do you plan after the talk session, as an example, or combined with the presentation talk?

**Comment by vasarhelyia** [comment]
1. Absolutely, 2. Sounds great! 

Let's do this on the 15th 👍
