### ISSUE TITLE
Talk proposal: Optimizing Swift Collections

### ISSUE THREAD

**Issue by lorentey** [NSBudapest/NSBudapestMeetup#22]
I gave a well-received 18-minute talk about five different ways to implement the same data structure on dotSwift 2017 in Paris last week. I talked about reusing existing Collections, building our own data structure from scratch using algebraic data types, implementing the copy-on-write optimization, then synthesizing what we learned by building a super fast data structure combining elements of each solution.

I'm still working on uploading the code & slides, but the raw Keynote deck is available on [my homepage](https://lorentey.hu/dotSwift-Karoly.key.zip). 

I think a slightly expanded, 30-minute talk on this same topic would make for a nice entry for the meetup.

**Comment by vasarhelyia** [comment]
awesome! how about this Wednesday? (15th) 😄

**Comment by lorentey** [comment]
Sure! Let's do it.  😁
