### ISSUE TITLE
Talk Proposal: Deep Learning on Mobile

### ISSUE THREAD

**Issue by jackflips** [NSBudapest/NSBudapestMeetup#23]
Hey! I'm an engineer at Clarifai, an AI startup in New York. I'll be visiting central Europe in early and mid-march so if it is possible to speak at a meetup during this time it would be perfect.

Talk abstract: It’s 2017, and computers can see. Still, it can be challenging to integrate deep learning into our apps. I’ll go over the best approaches, including Tensorflow, and show how the new Clarifai SDK makes it easy to train models in real-time on a device and share them among users.

**Comment by vasarhelyia** [comment]
Sounds great! :+1: We could make it work in mid-March, what dates are you going to be in Budapest? For us, tha later the better.

**Comment by gabornagyfarkas** [comment]
Wow, really interesting! 👍

**Comment by gabornagyfarkas** [comment]
Hi @jackflips! 

Are you in town and interested in a talk or should we close this issue?

**Comment by gabornagyfarkas** [comment]
I'm closing this issue, if you're still interested, please open a new one.
