### ISSUE TITLE
Static Code Analysis with Clang on iOS

### ISSUE THREAD

**Issue by gbrbks** [NSBudapest/NSBudapestMeetup#29]
My talk is about a possible approach to have a static code analysis framework with the help of the compiler in order to boost up the Code Quality and with that the overall product's quality.

**Comment by gabornagyfarkas** [comment]
Hi @hamutarto! 👋 

Thanks for your application! It's a really great topic 👍 
What do you think about July? For June the only plan is the WWDC keynote party.

**Comment by gbrbks** [comment]
Sure it's a good idea to have after wwdc! :)

**Comment by gabornagyfarkas** [comment]
Could you please prepare it for 27th July?

**Comment by gbrbks** [comment]
Unfortunately on 27th of July I'll be on holiday outside of Hungary :(

**Comment by gabornagyfarkas** [comment]
When do you leave?

**Comment by gabornagyfarkas** [comment]
@hamutarto what dates could work for you?

**Comment by gbrbks** [comment]
I'm free from now

**Comment by gabornagyfarkas** [comment]
Until when? So if 27th is not working for you, which is the latest date which is okay?

**Comment by gbrbks** [comment]
there is no planned holiday in July and August, so if the upcoming one will happen in these months i should available

**Comment by gabornagyfarkas** [comment]
@hamutarto can we fix the date - 31st of August?

**Comment by gbrbks** [comment]
@gabornagyfarkas Sure! :) Let's do it on 31st of August!
