### ISSUE TITLE
Proposal for my Shapr3D talk

### ISSUE THREAD

**Issue by istvan-csanady** [NSBudapest/NSBudapestMeetup#3]
How we redesigned the 3D modeling user experience from the ground up for the iPad Pro?

Shapr3D is a 3D modeling app for the iPad Pro. I will talk about the challenges of UI/UX design of a very complex application, about designing our interface for the Apple Pencil and multitouch interaction. I will briefly talk about the technical challenges of developing a CAD application on a mobile platform, about our technology stack, and about our experiences with the iPad Pro's amazing ARMv9 CPU.

Istvan is a software engineer and serial entrepreneur. He is the founder and CEO of Shapr3D.

**Comment by vasarhelyia** [comment]
👍

**Comment by viktorbenei** [comment]
👍

**Comment by bloodrabbit** [comment]
👍
