### ISSUE TITLE
Creating Your Own Programming Language with ANTLR

### ISSUE THREAD

**Issue by zskolbay** [NSBudapest/NSBudapestMeetup#30]
I'd like to give a talk about how to write your own (domain specific) language with ANTLR (http://www.antlr.org/) for iOS/Mac OS in Swift.

**Comment by lorentey** [comment]
👍yes please 🙂

**Comment by vasarhelyia** [comment]
sounds great! I think we'll have our next event in July, right, @gabornagyfarkas? (he's the one organizing it)

**Comment by gabornagyfarkas** [comment]
Hi! Yes we will have our next event in July, and @zskolbay this topic is more than welcome! Could you prepare it until the end of July?

**Comment by zskolbay** [comment]
I can prepare it, but I will be on the Faroe Islands between the 23rd of July and the 1st of August. Do you have an exact date for the meetup in July?

**Comment by gabornagyfarkas** [comment]
Yes, the meetups are at the last Thursday of the month. What do you think about August?

**Comment by zskolbay** [comment]
Great, the last week of August will be fine! That gives me plenty of time to prepare.

**Comment by zskolbay** [comment]
Just to be clear: the presentations are 30 minutes long, right?

**Comment by gabornagyfarkas** [comment]
Yes, 20-30 minutes :)

**Comment by zskolbay** [comment]
Thanks, I'll aim for 30 then :)

**Comment by gabornagyfarkas** [comment]
@zskolbay can we fix the date - 31st of August?

**Comment by zskolbay** [comment]
Aye aye, captain! I'll send you the abstract soon.

**Comment by gabornagyfarkas** [comment]
Thanks! 👍 🚀

**Comment by zskolbay** [comment]
# Zsolt Kolbay: Writing your own computer language for fun and profit

Learn how to create your own programming language in [Swift with ANTLR]!
ANTLR [(ANother Tool for Language Recognition)] is an open-source tool helps you define the grammar of your language and process it in Swift.
This presentation will show you how to create a [LOGO] interpreter with a syntax like this:
```	
repeat 5 {
	forward 150
	left 144
}
```	

[![N|Solid](https://image.ibb.co/mtxWxF/turtle_graphics.png)](https://nodesource.com/products/nsolid)
You will also learn how to express your business rules of your application in a language of your own.

   [LOGO]: <https://en.wikipedia.org/wiki/Logo_(programming_language)>
   [(ANother Tool for Language Recognition)]: <http://www.antlr.org/>
   [Swift with ANTLR]: <https://github.com/antlr/antlr4/blob/master/doc/swift-target.md>

**Comment by gabornagyfarkas** [comment]
Thanks!

**Comment by zskolbay** [comment]
I see the meetup will be held at SuperCharge. It's been a long time since I was there, so I have a couple of questions about before the presentation about the setup:
- do you know what is the projector's resolution is?
- is there a standing desk like at UStream where I do the presentation?

**Comment by gabornagyfarkas** [comment]
@zskolbay could you please give me your email address? I will send you out the details.

**Comment by zskolbay** [comment]
kolbay_zsolt@yahoo.com
