### ISSUE TITLE
Proposal for my Engineering talk

### ISSUE THREAD

**Issue by WiesnerPeti** [NSBudapest/NSBudapestMeetup#4]
Besides the giants like Facebook, Google and Twitter only a few smaller companies are able to work at scale. Skyscanner Budapest stepped on this exciting journey last year and set the goal: enable more and more engineers inside the company to work together on Skyscanner’s apps but at the same time keep our pace and fix release schedule that allows us iterative development.

My presentation aims to be an insider-tour in Skyscanner’s engineering culture and more specifically in the daily routine of our Budapest-based mobile app development team: we are 40 engineers working to satisfy the needs of over 40 million travellers. It is also a story about how we slowly evolved from coders to product engineers whose most important job is to creatively solve complex problems.

We haven't reached the end of our journey yet, however we think that our first learnings can be interesting for others.

Peter is a passionate software engineer. For the last 5 years he has worked in iOS development and contributed to the birth of several state of the art mobile applications under the flag of a Hungarian start-up, Distinction. Since the company’s acquisition by leading travel search engine Skyscanner in 2014, he has been leading iOS development teams and could also release his dream project, Dixie as the company’s first open source library.

**Comment by viktorbenei** [comment]
👍

**Comment by bloodrabbit** [comment]
👍
