### ISSUE TITLE
Proposal for my iOS layout talk

### ISSUE THREAD

**Issue by davidkovaccs** [NSBudapest/NSBudapestMeetup#5]
**Bulding large products from reusable components on iOS**

Creating applications with 100+ screens could seem impossible at glance. When you start thinking, it sounds like a good idea to create reusable components.
Assume, you have a great UX team who creates stylish, reusable UI components which could be used across multiple screens.
But how can we easily build screens from these components? Up until now iOS did not have a built-in, easy-to-use solution for creating and arranging these reusable components. Though there are several open-source solutions out there but none of them supports auto-layout.
We have developed a layout engine called SCComponentCollection that meant to solve this problem. It is lightweight and can be applied for various of use-cases. I will demonstrate the solution and share the motivations behind it along with architectural tips.
In the end I'll talk about the new way how it should be done in iOS9.

Agenda:
- Why do we need a layout engine?
- Available solutions
- Our solution - SCComponentCollection
- The iOS9 solution

**David Kovacs**
CTO
**Supercharge**

**Comment by viktorbenei** [comment]
👍

**Comment by fatalaa** [comment]
I'd like to hear about 👍

**Comment by bloodrabbit** [comment]
Sounds awesome! 🚀

**Comment by vasarhelyia** [comment]
👌
