### ISSUE TITLE
Proposal: Pursuing 60 FPS Scrolling

### ISSUE THREAD

**Issue by tzahola** [NSBudapest/NSBudapestMeetup#6]
We will talk about:
- Why your iOS scrolling experience sucks
- Why your Mac scrolling experience sucks
- Measure how much they suck
- How you can improve them to not suck

Motto: anything less than 60 fps is for Android

**Comment by vasarhelyia** [comment]
:+1:

**Comment by bloodrabbit** [comment]
Let's do this shit 👍
