### ISSUE TITLE
Proposal: How to release iOS apps every second week and do iOS staged rollout

### ISSUE THREAD

**Issue by CsabaSzabo** [NSBudapest/NSBudapestMeetup#7]
Topics to cover in my talk:
- setting the pace - how did we archive bi-weekly releases for millions of users at Skyscanner
- how to do staged rollout on iOS
- my good and bad experience with iTunes Connect
- how to automate your whole release process?
- are you confident when you push "Release This Version" button - how to support your iOS release with monitoring and alerting
- releasing iOS, Android or web apps - why are those different?

**Comment by vasarhelyia** [comment]
:+1:

**Comment by endanke** [comment]
Awesome, I'm really interested!

**Comment by CsabaSzabo** [comment]
we did it yesterday :)

**Comment by vasarhelyia** [comment]
It was awesome!
