### ISSUE TITLE
Proposal: Non-Pessimizations in the Swift compiler

### ISSUE THREAD

**Issue by H2CO3** [NSBudapest/NSBudapestMeetup#8]
I'd like to propose a talk about some interesting findings I've come across recently while studying the source of the Swift compiler. Topics that will be covered:
- A brief, lightweight introduction to the architecture of the Swift compiler, with special regards to the SIL CFG and SSA, for those unfamiliar with these concepts
- The importance of normalization of IR, and why I say "non-pessimization" rather than "optimization"
- Three interesting and clever non-pessimizations:
  - ARC optimizations
  - `inout` shadow variable elimination
  - Unification of closures and free functions

**Comment by vasarhelyia** [comment]
very nice! 👍
