### ISSUE TITLE
Proposal: Framework Oriented Programming

### ISSUE THREAD

**Issue by pepicrft** [NSBudapest/NSBudapestMeetup#9]
Hi!
I have a proposal about a topic I've been working on the last months. I created a reference for an architectural approach for Xcode project that I called "Framework Oriented Programming". The idea behind this architecture is organizing your apps in reusable local frameworks. Single purposes pieces of code, that could be shared on multiple platforms and by multiple products.

The reference is on this repository https://github.com/pepibumur/framework-oriented-programming whose points would be explained in the talk.

**Comment by lorentey** [comment]
I had been thinking along the same lines recently; I'd be very interested in this presentation!

**Comment by vasarhelyia** [comment]
👍

**Comment by pepicrft** [comment]
👏
